version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "SLOPortal"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-7ovwbg4gjz9b"
s3_prefix = "SLOPortal"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
